### ISSUE TITLE
bump version and republish gem?

### ISSUE THREAD

**Issue by GhostGambler** [paymill/paymill-ruby#1]
The `gem paymill` command installs an old version of the gem.

**Comment by Hates** [comment]
Any news on the RubyGems release? I can't currently use this repo in a gem I'm maintaining and have to resort to the dkd gem.

**Comment by morgoth** [comment]
Looks like `paymill` gem on rubygems https://rubygems.org/gems/paymill points to dkd repo.
Which one is official?
There are no commits on both repos for a whle.

**Comment by Hates** [comment]
@morgoth I believe this is the "official" repo but its sadly not available as a standalone gem, you can use it by using the github option in your `Gemfile`.

**Comment by morgoth** [comment]
I'm using dkd repo as I need a commit https://github.com/dkd/paymill-ruby/commit/3f18fd706909aad1b994a4c8d56ab2f085657e62 which is not present in this repo.

**Comment by nikoloff** [comment]
released under https://rubygems.org/gems/paymill_ruby
