### ISSUE TITLE
Backport missing webhook attributes

### ISSUE THREAD

**Issue by morgoth** [paymill/paymill-ruby#13]
I'm still using version from git from https://github.com/dkd/paymill-ruby
because of https://github.com/dkd/paymill-ruby/commit/3f18fd706909aad1b994a4c8d56ab2f085657e62

Can you please backport this commit?

**Comment by morgoth** [comment]
@nikoloff I can open PR with this backport if you willing to merge it.

**Comment by nikoloff** [comment]
Hi @morgoth 

we have the attributes [app_id](https://github.com/paymill/paymill-ruby/blob/master/lib/paymill/models/base.rb#L7) and [active](https://github.com/paymill/paymill-ruby/blob/master/lib/paymill/models/webhook.rb#L7) in this version. Are you using [paymill_ruby gem](https://rubygems.org/gems/paymill_ruby)?

**Comment by morgoth** [comment]
Yes, it's there - I was searching by commit history and not code. Thanks.
