### ISSUE TITLE
Simplified way of updating and deleting

### ISSUE THREAD

**Issue by morgoth** [paymill/paymill-ruby#15]
Currently to do `update` or `delete` you have to first `find` the resource. This API call is redundant and not needed at all. Do you think it would be possible to provide some way to avoid this request?

**Comment by nikoloff** [comment]
Hi @morgoth,
to update or delete a resource you need to have a reference to it (find it).

Can you be more clear about this. The only thing I can do is to provide class methods for update and delete, which work with String (the resource id).

**Comment by morgoth** [comment]
I found workaround by: `Paymill::Client.new(id: "client_id").delete` and the same with update:
```
client = Paymill::Client.new(id: "client_id")
client.description = "something"
client.update
```
BTW, sending attributes to update method `client.update(description: "something")` doesn't work, but I can open separate issue for this.

**Comment by nikoloff** [comment]
yes, pls ;)
