### ISSUE TITLE
Checksum with Client 

### ISSUE THREAD

**Issue by heinrichhanekom** [paymill/paymill-ruby#23]
Creating a checksum does not allow setting the client using the client_id

Paymill documentation: https://developers.paymill.com/guides/paypal/transactions.html
In the section "Optional transaction details"
client: PAYMILL client ID (e.g. "client_88a388d9dd48f86c3136"). A new transaction will create a new payment. If you specify a client, the new payment will be attached to it.

Issue location: https://github.com/paymill/paymill-ruby/blob/master/lib/paymill/models/checksum.rb

**Comment by nikoloff** [comment]
solved in version 2.0.1 of the gem
