### ISSUE TITLE
ActiveSupport 4.1 requirement

### ISSUE THREAD

**Issue by Hates** [paymill/paymill-ruby#7]
Is there any main reason that this requires ActiveSupport 4.1? This make is un-usable on any Rails project that's pre 4.1.

**Comment by nikoloff** [comment]
@Hates 

fix and released in rubugems under v1.0.2

**Comment by Hates** [comment]
@nikoloff Not to sound rude but this is worse than before as now you can't use the gem on anything but a Rails 4.2 project now where as at least before you could us it on 4.1. We are running Rails 4.0 which means we still can't use this.

**Comment by Hates** [comment]
Ah, just saw you removed the runtime dependency. Thanks a lot +1
