### ISSUE TITLE
Add explanation on how to run the spec

### ISSUE THREAD

**Issue by dsander** [paymill/paymill-ruby#9]
The usual `git clone`, `bundle`, `rake` combination fails horribly. Reading the spec helper I was able to figure out that an API token is needed.

Even with the token the specs are failing because some specs expect objects to be present in your paymill account.

It would be great if you could change the specs to either first create the expected objects or add working cassettes to the repository and disable the `re_record_interval` option of VCR.

Thanks

**Comment by morgoth** [comment]
Probably the best way would be to record cassettes and include them in repository. This way it could also run on CI.
Currently it's impossible to run test suite.

**Comment by nikoloff** [comment]
Hi @morgoth 

In the current master there are no hardcoded ids and PAYMILL keys, so you are now able to run the test suite on your local machine. Pls check again the [Contributing section](https://github.com/paymill/paymill-ruby#contributing)

**Comment by morgoth** [comment]
Yes, I did and it runs fine.
However it's still impossible to run it on travis - don't you think that it would be better to check in cassettes to repository?

**Comment by nikoloff** [comment]
I really don't want to check in the cassettes.
On travis it is failing because of the concurrent builds, which I have disabled right and it runs the suite sequential. So I expect that it won't fail anymore
